stages:
  - build
  - deploy

build_image:
  stage: build
  script:
    - docker build --build-arg MC_VERSION=${CI_COMMIT_REF_NAME} --tag ${GITLAB_USER_LOGIN}/${CI_PROJECT_NAME,,}:${CI_COMMIT_REF_NAME} .

deploy_image:
  stage: deploy
  script:
    - docker push ${GITLAB_USER_LOGIN}/${CI_PROJECT_NAME,,}:${CI_COMMIT_REF_NAME}